# Test Cases

In [8]:
# Test Case 1: Add Books to the Library

# Add a new book
add_book("Learning Python", "Mark Lutz", 3)
print("After adding 'Learning Python' by 'Mark Lutz':")
books_df

After adding 'Learning Python' by 'Mark Lutz':

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,5
2,Data Science with Python,Jane Smith,3
3,Machine Learning Basics,Michael Brown,4
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7
7,Clean Code,Robert C. Martin,5
8,Design Patterns,Erich Gamma,4
9,JavaScript: The Good Parts,Douglas Crockford,3
10,The Pragmatic Programmer,Andrew Hunt,8
11,Learning Python,Mark Lutz,3

In [9]:
# Add an existing book with additional copies
add_book("Python Programming", "John Doe", 2)
print("\nAfter adding 2 more copies of 'Python Programming' by 'John Doe':")
books_df

After adding 2 more copies of 'Python Programming' by 'John Doe':

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,7
2,Data Science with Python,Jane Smith,3
3,Machine Learning Basics,Michael Brown,4
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7
7,Clean Code,Robert C. Martin,5
8,Design Patterns,Erich Gamma,4
9,JavaScript: The Good Parts,Douglas Crockford,3
10,The Pragmatic Programmer,Andrew Hunt,8
11,Learning Python,Mark Lutz,3

In [10]:
# Test Case 2: Add Users to the System

# Add a new user
add_user("John", "Smith", 25, "Male")
print("\nAfter adding 'John Smith':")
users_df

After adding 'John Smith':

,First Name,Last Name,Age,Role,Borrowed Books,Fines,Gender
0,Leen,Samman,20,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
1,Amal,Taha,34,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
2,Amany,Awwad,22,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
3,Ahmad,Bilal,55,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male
4,Karam,Jallad,19,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male
5,Qamar,Sayeed,33,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
6,Hayat,Najjar,19,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
7,Tamara,Mousa,36,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
8,Omar,Bilal,28,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male
9,Amjad,Rami,41,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male
10,John,Smith,25,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male

In [11]:
# Attempt to add the same user again
add_user("John", "Smith", 25, "Male")
print("\nAfter trying to add 'John Smith' again:")
users_df

User John Smith already exists.

After trying to add 'John Smith' again:

,First Name,Last Name,Age,Role,Borrowed Books,Fines,Gender
0,Leen,Samman,20,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
1,Amal,Taha,34,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
2,Amany,Awwad,22,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
3,Ahmad,Bilal,55,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male
4,Karam,Jallad,19,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male
5,Qamar,Sayeed,33,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
6,Hayat,Najjar,19,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
7,Tamara,Mousa,36,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
8,Omar,Bilal,28,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male
9,Amjad,Rami,41,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male
10,John,Smith,25,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male

In [12]:
# Test Case 3: Borrow a Book
# there is a case that the code does not handle
# the case indicate the the user could borrow the same at the same time
# for every cell run the copies will be decreased

# Create a user instance
john_smith = users("John", "Smith", 25, "Male")

# John borrows "Python Programming" by "John Doe" for 15 days
john_smith.borrow_book("Python Programming", "John Doe", 15)
print("\nAfter 'John Smith' borrows 'Python Programming':")
print(borrowed_books_df)
books_df

Python Programming by John Doe has been borrowed until 2024-09-06.
Current Date: 2024-08-22 17:02:03.226568
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []

After 'John Smith' borrows 'Python Programming':
         User               Title    Author Borrow Date    Due Date
0  John Smith  Python Programming  John Doe  2024-08-22  2024-09-06

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,6
2,Data Science with Python,Jane Smith,3
3,Machine Learning Basics,Michael Brown,4
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7
7,Clean Code,Robert C. Martin,5
8,Design Patterns,Erich Gamma,4
9,JavaScript: The Good Parts,Douglas Crockford,3
10,The Pragmatic Programmer,Andrew Hunt,8
11,Learning Python,Mark Lutz,3

In [13]:
# Test Case 4: Return a Book

# John returns "Python Programming" by "John Doe"
john_smith.return_book("Python Programming", "John Doe")
print("\nAfter 'John Smith' returns 'Python Programming':")
borrowed_books_df

Python Programming by John Doe has been returned.
Current Date: 2024-08-22 17:02:03.244208
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []

After 'John Smith' returns 'Python Programming':

Empty DataFrame
Columns: [User, Title, Author, Borrow Date, Due Date]
Index: []

In [14]:
books_df

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,7
2,Data Science with Python,Jane Smith,3
3,Machine Learning Basics,Michael Brown,4
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7
7,Clean Code,Robert C. Martin,5
8,Design Patterns,Erich Gamma,4
9,JavaScript: The Good Parts,Douglas Crockford,3
10,The Pragmatic Programmer,Andrew Hunt,8
11,Learning Python,Mark Lutz,3

In [15]:
transaction_log_df

  Transaction Type        User               Title    Author Transaction Date
0           Borrow  John Smith  Python Programming  John Doe       2024-08-22
1           Return  John Smith  Python Programming  John Doe       2024-08-22

In [16]:
# Test Case 5: Reserve a Book

# First, we'll borrow all copies of "Machine Learning Basics" by "Michael Brown" to ensure no copies are available.
leen_samman = users("Leen", "Samman", 20, "Female")
for _ in range(4):  # Assuming there are 4 copies available
    leen_samman.borrow_book("Machine Learning Basics", "Michael Brown", 10)

# Now, John tries to reserve "Machine Learning Basics"
john_smith.reserve_book("Machine Learning Basics", "Michael Brown")
print("\nAfter 'John Smith' reserves 'Machine Learning Basics':")
reservations_df

Machine Learning Basics by Michael Brown has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.289045
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
Machine Learning Basics by Michael Brown has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.294043
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
Machine Learning Basics by Michael Brown has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.297043
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
Machine Learning Basics by Michael Brown has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.302044
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
Queue positions updated for 'Machine Learning Basics' by Michael Brown.
'Machine Learning Basics' by Michael Brown has been reserved.

After 'John Smith' reserves 'Machine Learning Basics':

,Title,Author,Reserved By,Reservation Date,Queue Position,Notification Sent
0,Machine Learning Basics,Michael Brown,John Smith,2024-08-22,1,False

In [17]:
# Test Case 6: Cancel a Reservation

# Step 1: John reserves "Machine Learning Basics" by "Michael Brown"
john_smith.reserve_book("Machine Learning Basics", "Michael Brown")

# Step 2: John cancels his reservation for "Machine Learning Basics"
john_smith.cancel_reservation("Machine Learning Basics", "Michael Brown")
print("\nAfter 'John Smith' cancels his reservation for 'Machine Learning Basics':")
reservations_df

Queue positions updated for 'Machine Learning Basics' by Michael Brown.
'Machine Learning Basics' by Michael Brown has been reserved.
Reservation for 'Machine Learning Basics' by Michael Brown has been canceled.
'Machine Learning Basics' by Michael Brown is still borrowed by another user, but your cancellation was successful.

After 'John Smith' cancels his reservation for 'Machine Learning Basics':

Empty DataFrame
Columns: [Title, Author, Reserved By, Reservation Date, Queue Position, Notification Sent]
Index: []

In [18]:
# Test Case 7: Multiple Reservations with Three Users and Assigning a Book to the Next User in the Queue

# Step 1: Ensure all copies of "Machine Learning Basics" are borrowed
leen_samman = users("Leen", "Samman", 20, "Female")
for _ in range(4):  # Assuming there are 4 copies available
    leen_samman.borrow_book("Machine Learning Basics", "Michael Brown", 10)

# Step 2: John Smith reserves "Machine Learning Basics"
john_smith.reserve_book("Machine Learning Basics", "Michael Brown")

# Step 3: User 2 reserves "Machine Learning Basics"
user2 = users("layla", "ali", 30, "Male")
user2.reserve_book("Machine Learning Basics", "Michael Brown")

# Step 4: User 3 reserves "Machine Learning Basics"
user3 = users("dina", "karam", 25, "Female")
user3.reserve_book("Machine Learning Basics", "Michael Brown")

# Check the reservation queue before the book is returned
print("\nReservation queue before returning the book:")
reservations_df

No copies of 'Machine Learning Basics' by Michael Brown are currently available.
Current Date: 2024-08-22 17:02:03.340746
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
No copies of 'Machine Learning Basics' by Michael Brown are currently available.
Current Date: 2024-08-22 17:02:03.342748
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
No copies of 'Machine Learning Basics' by Michael Brown are currently available.
Current Date: 2024-08-22 17:02:03.343748
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
No copies of 'Machine Learning Basics' by Michael Brown are currently available.
Current Date: 2024-08-22 17:02:03.344747
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
Queue positions updated for 'Machine Learning Basics' by Michael Brown.
'Machine Learning Basics' by Michael Brown has been reserved.
Queue positions updated for 'Machine Learning Basics' by Michael Brown.
'Machine Learning Basics' by Michael Brown has been reserved.
Queue positions updated for 'Machine Learning Basics' by Michael Brown.
'Machine Learning Basics' by Michael Brown has been reserved.

Reservation queue before returning the book:

,Title,Author,Reserved By,Reservation Date,Queue Position,Notification Sent
0,Machine Learning Basics,Michael Brown,John Smith,2024-08-22,1,False
1,Machine Learning Basics,Michael Brown,layla ali,2024-08-22,2,False
2,Machine Learning Basics,Michael Brown,dina karam,2024-08-22,3,False

In [19]:
# Step 5: Leen Samman returns a copy of "Machine Learning Basics"
leen_samman.return_book("Machine Learning Basics", "Michael Brown")

# Check the reservation queue and borrowed books after the book is returned
print("\nReservation queue after returning the book:")
reservations_df

Machine Learning Basics by Michael Brown has been returned.
Notification: 'Machine Learning Basics' by Michael Brown is now available for John Smith.
Machine Learning Basics by Michael Brown has been borrowed until 2024-09-21.
Current Date: 2024-08-22 17:02:03.377661
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
Current Date: 2024-08-22 17:02:03.379661
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []

Reservation queue after returning the book:

,Title,Author,Reserved By,Reservation Date,Queue Position,Notification Sent
0,Machine Learning Basics,Michael Brown,John Smith,2024-08-22,1,True
1,Machine Learning Basics,Michael Brown,layla ali,2024-08-22,2,False
2,Machine Learning Basics,Michael Brown,dina karam,2024-08-22,3,False

In [20]:
print("\nBorrowed books after returning the book:")
borrowed_books_df

Borrowed books after returning the book:

         User                    Title         Author Borrow Date    Due Date
0  John Smith  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-21

In [21]:
# The overdue book handling test case was not executed because the due date 
# falls on the current date, and the system correctly does not apply fines 
# when the due date is today.

In [22]:
# Test Case: Admin Deletes a Book Record

# Step 1: Admin adds "Data Science with Python" by "Jane Smith" to the library
admin = Admin("Admin", "User", 40, "Male")
admin.add_book("Data Science with Python", "Jane Smith", 5)

# Step 2: User (laya abed) borrows the book
laya_abed = users("Laya", "abed", 22, "Female")
laya_abed.borrow_book("Data Science with Python", "Jane Smith", 10)

# Step 3: Another user (Zaina Abunasser) reserves the book
sima_abunassar = users("Sima", "Abunassar", 23, "Female")
sima_abunassar.reserve_book("Data Science with Python", "Jane Smith")

# Step 4: Admin deletes the "Data Science with Python" book record
admin.delete_book_record("Data Science with Python", "Jane Smith")

# Step 5: Validate that the book record is deleted
print("\nBooks DataFrame after deletion:")
books_df

Copies of 'Data Science with Python' by Jane Smith have been increased by 5. Total copies available: 8
Data Science with Python by Jane Smith has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.413039
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
'Data Science with Python' by Jane Smith is currently available, no need to reserve.
All copies of 'Data Science with Python' by Jane Smith have been deleted from the library.

Books DataFrame after deletion:

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,7
3,Machine Learning Basics,Michael Brown,0
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7
7,Clean Code,Robert C. Martin,5
8,Design Patterns,Erich Gamma,4
9,JavaScript: The Good Parts,Douglas Crockford,3
10,The Pragmatic Programmer,Andrew Hunt,8
11,Learning Python,Mark Lutz,3

In [23]:
# Validate that the reservation for the book is also removed
print("\nReservations DataFrame after deletion:")
reservations_df

Reservations DataFrame after deletion:

,Title,Author,Reserved By,Reservation Date,Queue Position,Notification Sent
0,Machine Learning Basics,Michael Brown,John Smith,2024-08-22,1,True
1,Machine Learning Basics,Michael Brown,layla ali,2024-08-22,2,False
2,Machine Learning Basics,Michael Brown,dina karam,2024-08-22,3,False

In [24]:
# Validate that the borrowed book record is handled correctly
print("\nBorrowed Books DataFrame after deletion:")
borrowed_books_df

Borrowed Books DataFrame after deletion:

         User                     Title         Author Borrow Date    Due Date
0  John Smith   Machine Learning Basics  Michael Brown  2024-08-22  2024-09-21
1   Laya abed  Data Science with Python     Jane Smith  2024-08-22  2024-09-01

In [25]:
# Test Case: Admin Tries to Delete a Non-Existent Book Record

# Step 1: Admin tries to delete a book that does not exist in the library
admin = Admin("Admin", "User", 40, "Male")
admin.delete_book_record("Advanced AI Concepts", "Unknown Author")

# Step 2: Validate that the system handled the case appropriately
print("\nBooks DataFrame after attempting to delete a non-existent book:")
books_df

Book 'Advanced AI Concepts' by Unknown Author does not exist in the library.

Books DataFrame after attempting to delete a non-existent book:

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,7
3,Machine Learning Basics,Michael Brown,0
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7
7,Clean Code,Robert C. Martin,5
8,Design Patterns,Erich Gamma,4
9,JavaScript: The Good Parts,Douglas Crockford,3
10,The Pragmatic Programmer,Andrew Hunt,8
11,Learning Python,Mark Lutz,3

In [26]:
# Test Case: Admin Adds a Duplicate Book Record . the copies will increase 

# Step 1: Admin adds "Deep Learning with Python" by "Francois Chollet" to the library
admin = Admin("Admin", "User", 40, "Male")
admin.add_book("Deep Learning with Python", "Francois Chollet", 3)

# Step 2: Admin tries to add the same book again to check for duplication
admin.add_book("Deep Learning with Python", "Francois Chollet", 3)

# Step 3: Validate that the system handled the case appropriately
print("\nBooks DataFrame after attempting to add a duplicate book:")
books_df

Book 'Deep Learning with Python' by Francois Chollet has been added with 3 copies.
Copies of 'Deep Learning with Python' by Francois Chollet have been increased by 3. Total copies available: 6

Books DataFrame after attempting to add a duplicate book:

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,7
3,Machine Learning Basics,Michael Brown,0
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7
7,Clean Code,Robert C. Martin,5
8,Design Patterns,Erich Gamma,4
9,JavaScript: The Good Parts,Douglas Crockford,3
10,Deep Learning with Python,Francois Chollet,6
11,Learning Python,Mark Lutz,3

In [27]:
# Test Case: Admin Decrements the Number of Copies for a Book


# Step 2: Admin decrements the number of copies by 1.
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")

# Step 3: Admin attempts to decrement the number of copies until there's only one copy left.
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")

# Step 4: Admin attempts to decrement the last remaining copy and validate the system’s behavior.
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")

# Validate the final state of the book record in the library.
print("\nBooks DataFrame after decrementing copies:")
books_df

One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 5 copies remain.
One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 4 copies remain.
One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 3 copies remain.
One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 2 copies remain.
One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 1 copies remain.

Books DataFrame after decrementing copies:

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,7
3,Machine Learning Basics,Michael Brown,0
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7
7,Clean Code,Robert C. Martin,5
8,Design Patterns,Erich Gamma,4
9,JavaScript: The Good Parts,Douglas Crockford,3
10,Deep Learning with Python,Francois Chollet,1
11,Learning Python,Mark Lutz,3

In [28]:
# Test Case: Admin Decrements the Number of Copies for a Book

# Step 1: Admin adds the book "Deep Learning with Python" by "Francois Chollet" to the library with 5 copies.
admin = Admin("Admin", "User", 40, "Male")
admin.add_book("Deep Learning with Python", "Francois Chollet", 5)

# Step 2: Admin decrements the number of copies by 1.
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")

# Step 3: Admin attempts to decrement the number of copies until there's only one copy left.
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")

# Step 4: Admin attempts to decrement the last remaining copy and validate the system’s behavior.
admin.decrement_copies("Deep Learning with Python", "Francois Chollet")

# Validate the final state of the book record in the library.
print("\nBooks DataFrame after decrementing copies:")
books_df

Copies of 'Deep Learning with Python' by Francois Chollet have been increased by 5. Total copies available: 6
One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 5 copies remain.
One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 4 copies remain.
One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 3 copies remain.
One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 2 copies remain.
One copy of 'Deep Learning with Python' by Francois Chollet has been deleted. 1 copies remain.

Books DataFrame after decrementing copies:

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,7
3,Machine Learning Basics,Michael Brown,0
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7
7,Clean Code,Robert C. Martin,5
8,Design Patterns,Erich Gamma,4
9,JavaScript: The Good Parts,Douglas Crockford,3
10,Deep Learning with Python,Francois Chollet,1
11,Learning Python,Mark Lutz,3

In [29]:
# Test Case: User Cancels a Reservation

# Step 1: Admin adds the book "The Pragmatic Programmer" by "Andrew Hunt" to the library with 2 copies.
admin = Admin("Admin", "User", 40, "Male")
admin.add_book("The Pragmatic Programmer", "Andrew Hunt", 2)

# Step 2: User 1 (Karan Saeed) borrows one copy.
karan_saeed = users("Karan", "Saeed", 21, "Female")
karan_saeed.borrow_book("The Pragmatic Programmer", "Andrew Hunt", 10)

# Step 3: User 2 (Kinan Hamad) borrows the second copy.
kinan_hamad = users("Kinan", "Hamad", 22, "Male")
kinan_hamad.borrow_book("The Pragmatic Programmer", "Andrew Hunt", 10)

# Step 4: User 3 (Emad Dahleh) reserves the book.
emad_dahleh = users("Emad", "Dahleh", 23, "Male")
emad_dahleh.reserve_book("The Pragmatic Programmer", "Andrew Hunt")

# Step 5: User 4 (Amjad Talal) reserves the book.
amjad_talal = users("Amjad", "Talal", 28, "Male")
amjad_talal.reserve_book("The Pragmatic Programmer", "Andrew Hunt")

# Step 6: User 3 (Emad Dahleh) decides to cancel his reservation.
emad_dahleh.cancel_reservation("The Pragmatic Programmer", "Andrew Hunt")


# Step 7: Validate that User 4 (Amjad Talal) is now first in the reservation queue.
print("\nReservations DataFrame after Emad Dahleh cancels his reservation:")
reservations_df

Book 'The Pragmatic Programmer' by Andrew Hunt has been added with 2 copies.
The Pragmatic Programmer by Andrew Hunt has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.563086
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
The Pragmatic Programmer by Andrew Hunt has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.570084
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
Queue positions updated for 'The Pragmatic Programmer' by Andrew Hunt.
'The Pragmatic Programmer' by Andrew Hunt has been reserved.
Queue positions updated for 'The Pragmatic Programmer' by Andrew Hunt.
'The Pragmatic Programmer' by Andrew Hunt has been reserved.
Reservation for 'The Pragmatic Programmer' by Andrew Hunt has been canceled.
'The Pragmatic Programmer' by Andrew Hunt is still borrowed by another user, but your cancellation was successful.

Reservations DataFrame after Emad Dahleh cancels his reservation:

,Title,Author,Reserved By,Reservation Date,Queue Position,Notification Sent
0,Machine Learning Basics,Michael Brown,John Smith,2024-08-22,1,True
1,Machine Learning Basics,Michael Brown,layla ali,2024-08-22,2,False
2,Machine Learning Basics,Michael Brown,dina karam,2024-08-22,3,False
4,The Pragmatic Programmer,Andrew Hunt,Amjad Talal,2024-08-22,None,False

In [30]:
# Step 8: Validate that User 3 (Emad Dahleh) has no reservations in the system.
print("\nReserved Books for Emad Dahleh:")
emad_dahleh.display_reserved_books()

Reserved Books for Emad Dahleh:
No books currently reserved.

In [31]:
# Test Case: User Returns a Reserved Book

# Step 1: Admin adds the book "Data Structures and Algorithms" by "Mark Allen Weiss" to the library with 3 copies.
admin = Admin("Admin", "User", 40, "Male")
admin.add_book("Data Structures and Algorithms", "Mark Allen Weiss", 3)

# Step 2: User 1 (Karan Saeed) borrows one copy.
karan_saeed = users("Karan", "Saeed", 21, "Female")
karan_saeed.borrow_book("Data Structures and Algorithms", "Mark Allen Weiss", 10)

# Step 3: User 2 (Kinan Hamad) borrows another copy.
kinan_hamad = users("Kinan", "Hamad", 22, "Male")
kinan_hamad.borrow_book("Data Structures and Algorithms", "Mark Allen Weiss", 10)

# Step 4: User 3 (Emad Dahleh) reserves the book.
emad_dahleh = users("Emad", "Dahleh", 23, "Male")
emad_dahleh.reserve_book("Data Structures and Algorithms", "Mark Allen Weiss")

# Step 5: User 1 (Karan Saeed) returns the book.
karan_saeed.return_book("Data Structures and Algorithms", "Mark Allen Weiss")

# Step 6: Validate that User 3 (Emad Dahleh) receives a notification that the book is now available.
print("\nReservations DataFrame after Karan Saeed returns the book:")
reservations_df

Book 'Data Structures and Algorithms' by Mark Allen Weiss has been added with 3 copies.
Data Structures and Algorithms by Mark Allen Weiss has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.610188
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
Data Structures and Algorithms by Mark Allen Weiss has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.617204
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
'Data Structures and Algorithms' by Mark Allen Weiss is currently available, no need to reserve.
Data Structures and Algorithms by Mark Allen Weiss has been returned.
Current Date: 2024-08-22 17:02:03.624194
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []

Reservations DataFrame after Karan Saeed returns the book:

,Title,Author,Reserved By,Reservation Date,Queue Position,Notification Sent
0,Machine Learning Basics,Michael Brown,John Smith,2024-08-22,1,True
1,Machine Learning Basics,Michael Brown,layla ali,2024-08-22,2,False
2,Machine Learning Basics,Michael Brown,dina karam,2024-08-22,3,False
4,The Pragmatic Programmer,Andrew Hunt,Amjad Talal,2024-08-22,None,False

In [32]:
print("\nBorrowed Books DataFrame after the return and re-borrow:")
borrowed_books_df

Borrowed Books DataFrame after the return and re-borrow:

,User,Title,Author,Borrow Date,Due Date
0,John Smith,Machine Learning Basics,Michael Brown,2024-08-22,2024-09-21
1,Laya abed,Data Science with Python,Jane Smith,2024-08-22,2024-09-01
2,Karan Saeed,The Pragmatic Programmer,Andrew Hunt,2024-08-22,2024-09-01
3,Kinan Hamad,The Pragmatic Programmer,Andrew Hunt,2024-08-22,2024-09-01
5,Kinan Hamad,Data Structures and Algorithms,Mark Allen Weiss,2024-08-22,2024-09-01

In [33]:
# Admin Test Case: Running All Functions

# Step 1: Admin logs in and adds a new book
admin = Admin("Admin", "User", 40, "Male")
admin.add_book("The Pragmatic Programmer", "Andrew Hunt", 2)
admin.add_book("Clean Code", "Robert C. Martin", 5)

# Step 2: Admin views all books to verify the additions
print("\nAll Books in the Library after additions:")
admin.display_all_books()

# Step 3: Admin adds a user (Karan Saeed)
karan_saeed = users("Karan", "Saeed", 21, "Female")

# Step 4: Admin views all users
print("\nAll Users in the System after adding Karan Saeed:")
admin.display_all_users()

# Step 5: Karan Saeed borrows "Clean Code"
karan_saeed.borrow_book("Clean Code", "Robert C. Martin", 10)

# Step 6: Another user (Kinan Hamad) reserves "Clean Code"
kinan_hamad = users("Kinan", "Hamad", 22, "Male")
kinan_hamad.reserve_book("Clean Code", "Robert C. Martin")

# Step 7: Admin views all reservations
print("\nAll Reservations in the System:")
admin.display_all_reservations()

# Step 8: Admin views all borrowed books
print("\nAll Borrowed Books in the System:")
admin.display_all_borrowed_books()

# Step 9: Admin deletes the book "The Pragmatic Programmer"
admin.delete_book_record("The Pragmatic Programmer", "Andrew Hunt")

Book 'The Pragmatic Programmer' by Andrew Hunt has been added with 2 copies.
Copies of 'Clean Code' by Robert C. Martin have been increased by 5. Total copies available: 10

All Books in the Library after additions:
All Books in the Library:
                                     Title            Author  CopiesAvailable
                        Python Programming          John Doe                7
                   Machine Learning Basics     Michael Brown                0
             Deep Learning with TensorFlow        Anna White                2
Artificial Intelligence: A Modern Approach       Peter Green                6
                Introduction to Algorithms  Thomas H. Cormen                7
                                Clean Code  Robert C. Martin               10
                           Design Patterns       Erich Gamma                4
                JavaScript: The Good Parts Douglas Crockford                3
                  The Pragmatic Programmer       Andrew Hunt                2
                           Learning Python         Mark Lutz                3

All Users in the System after adding Karan Saeed:
All Users Data:
First Name Last Name Age    Role                                                                                                                                                                                                                                                                                                                            Borrowed Books Fines Gender
      Leen    Samman  20 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
      Amal      Taha  34 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
     Amany     Awwad  22 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
     Ahmad     Bilal  55 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
     Karam    Jallad  19 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
     Qamar    Sayeed  33 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
     Hayat    Najjar  19 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
    Tamara     Mousa  36 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
      Omar     Bilal  28 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
     Amjad      Rami  41 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
      John     Smith  25 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
      John     Smith  25 Regular                                                                                                                                                                                                                                      Book Title    Author Borrow Date Return Date
0  Python Programming  John Doe  2024-08-22  2024-09-06     0   Male
      Leen    Samman  20 Regular                 Book Title         Author Borrow Date Return Date
0  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-01
1  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-01
2  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-01
3  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-01     0 Female
      Leen    Samman  20 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0 Female
     layla       ali  30 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
      dina     karam  25 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0 Female
      John     Smith  25 Regular                                                                                                                                                                                                                       Book Title         Author Borrow Date Return Date
0  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-21     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
      Laya      abed  22 Regular                                                                                                                                                                                                                            Book Title      Author Borrow Date Return Date
0  Data Science with Python  Jane Smith  2024-08-22  2024-09-01     0 Female
      Sima Abunassar  23 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0 Female
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Karan     Saeed  21 Regular                                                                                                                                                                                                                          Book Title       Author Borrow Date Return Date
0  The Pragmatic Programmer  Andrew Hunt  2024-08-22  2024-09-01     0 Female
     Kinan     Hamad  22 Regular                                                                                                                                                                                                                          Book Title       Author Borrow Date Return Date
0  The Pragmatic Programmer  Andrew Hunt  2024-08-22  2024-09-01     0   Male
      Emad    Dahleh  23 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Amjad     Talal  28 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Karan     Saeed  21 Regular                                                                                                                                                                                                          Book Title            Author Borrow Date Return Date
0  Data Structures and Algorithms  Mark Allen Weiss  2024-08-22  2024-09-01     0 Female
     Kinan     Hamad  22 Regular                                                                                                                                                                                                          Book Title            Author Borrow Date Return Date
0  Data Structures and Algorithms  Mark Allen Weiss  2024-08-22  2024-09-01     0   Male
      Emad    Dahleh  23 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Karan     Saeed  21 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0 Female
Clean Code by Robert C. Martin has been borrowed until 2024-09-01.
Current Date: 2024-08-22 17:02:03.671870
Identified Overdue Books:
Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []
'Clean Code' by Robert C. Martin is currently available, no need to reserve.

All Reservations in the System:
All Reservations:
                   Title        Author Reserved By Reservation Date Queue Position  Notification Sent
 Machine Learning Basics Michael Brown  John Smith       2024-08-22              1               True
 Machine Learning Basics Michael Brown   layla ali       2024-08-22              2              False
 Machine Learning Basics Michael Brown  dina karam       2024-08-22              3              False
The Pragmatic Programmer   Andrew Hunt Amjad Talal       2024-08-22           None              False

All Borrowed Books in the System:
All Borrowed Books:
       User                    Title           Author Borrow Date   Due Date
 John Smith  Machine Learning Basics    Michael Brown  2024-08-22 2024-09-21
  Laya abed Data Science with Python       Jane Smith  2024-08-22 2024-09-01
Karan Saeed The Pragmatic Programmer      Andrew Hunt  2024-08-22 2024-09-01
Kinan Hamad The Pragmatic Programmer      Andrew Hunt  2024-08-22 2024-09-01
Karan Saeed               Clean Code Robert C. Martin  2024-08-22 2024-09-01
All copies of 'The Pragmatic Programmer' by Andrew Hunt have been deleted from the library.

In [34]:
# Step 10: Admin views all books to verify the deletion
print("\nAll Books in the Library after deletion:")
admin.display_all_books()

All Books in the Library after deletion:
All Books in the Library:
                                     Title            Author  CopiesAvailable
                        Python Programming          John Doe                7
                   Machine Learning Basics     Michael Brown                0
             Deep Learning with TensorFlow        Anna White                2
Artificial Intelligence: A Modern Approach       Peter Green                6
                Introduction to Algorithms  Thomas H. Cormen                7
                                Clean Code  Robert C. Martin                9
                           Design Patterns       Erich Gamma                4
                JavaScript: The Good Parts Douglas Crockford                3
                           Learning Python         Mark Lutz                3

In [35]:
# Step 12: Admin views all users to verify the deletion
print("\nAll Users in the System after deleting Karan Saeed:")
admin.display_all_users()

All Users in the System after deleting Karan Saeed:
All Users Data:
First Name Last Name Age    Role                                                                                                                                                                                                                                                                                                                            Borrowed Books Fines Gender
      Leen    Samman  20 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
      Amal      Taha  34 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
     Amany     Awwad  22 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
     Ahmad     Bilal  55 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
     Karam    Jallad  19 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
     Qamar    Sayeed  33 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
     Hayat    Najjar  19 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
    Tamara     Mousa  36 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0 Female
      Omar     Bilal  28 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
     Amjad      Rami  41 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
      John     Smith  25 Regular                                                                                                                                                                                                                                              Empty DataFrame\nColumns: [Book Title, First Date to Borrow, Last Date to Return]\nIndex: []     0   Male
      John     Smith  25 Regular                                                                                                                                                                                                                                      Book Title    Author Borrow Date Return Date
0  Python Programming  John Doe  2024-08-22  2024-09-06     0   Male
      Leen    Samman  20 Regular                 Book Title         Author Borrow Date Return Date
0  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-01
1  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-01
2  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-01
3  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-01     0 Female
      Leen    Samman  20 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0 Female
     layla       ali  30 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
      dina     karam  25 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0 Female
      John     Smith  25 Regular                                                                                                                                                                                                                       Book Title         Author Borrow Date Return Date
0  Machine Learning Basics  Michael Brown  2024-08-22  2024-09-21     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
      Laya      abed  22 Regular                                                                                                                                                                                                                            Book Title      Author Borrow Date Return Date
0  Data Science with Python  Jane Smith  2024-08-22  2024-09-01     0 Female
      Sima Abunassar  23 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0 Female
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Karan     Saeed  21 Regular                                                                                                                                                                                                                          Book Title       Author Borrow Date Return Date
0  The Pragmatic Programmer  Andrew Hunt  2024-08-22  2024-09-01     0 Female
     Kinan     Hamad  22 Regular                                                                                                                                                                                                                          Book Title       Author Borrow Date Return Date
0  The Pragmatic Programmer  Andrew Hunt  2024-08-22  2024-09-01     0   Male
      Emad    Dahleh  23 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Amjad     Talal  28 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Karan     Saeed  21 Regular                                                                                                                                                                                                          Book Title            Author Borrow Date Return Date
0  Data Structures and Algorithms  Mark Allen Weiss  2024-08-22  2024-09-01     0 Female
     Kinan     Hamad  22 Regular                                                                                                                                                                                                          Book Title            Author Borrow Date Return Date
0  Data Structures and Algorithms  Mark Allen Weiss  2024-08-22  2024-09-01     0   Male
      Emad    Dahleh  23 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Admin      User  40   Admin                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male
     Karan     Saeed  21 Regular                                                                                                                                                                                                                              Book Title            Author Borrow Date Return Date
0  Clean Code  Robert C. Martin  2024-08-22  2024-09-01     0 Female
     Kinan     Hamad  22 Regular                                                                                                                                                                                                                                                         Empty DataFrame
Columns: [Book Title, Author, Borrow Date, Return Date]
Index: []     0   Male

In [36]:
# Step 13: Admin views all transactions
print("\nAll Transactions in the System:")
admin.display_all_transactions()

All Transactions in the System:
All Transactions:
Transaction Type        User                          Title           Author Transaction Date
          Borrow  John Smith             Python Programming         John Doe       2024-08-22
          Return  John Smith             Python Programming         John Doe       2024-08-22
          Borrow Leen Samman        Machine Learning Basics    Michael Brown       2024-08-22
          Borrow Leen Samman        Machine Learning Basics    Michael Brown       2024-08-22
          Borrow Leen Samman        Machine Learning Basics    Michael Brown       2024-08-22
          Borrow Leen Samman        Machine Learning Basics    Michael Brown       2024-08-22
          Return Leen Samman        Machine Learning Basics    Michael Brown       2024-08-22
          Borrow  John Smith        Machine Learning Basics    Michael Brown       2024-08-22
          Borrow   Laya abed       Data Science with Python       Jane Smith       2024-08-22
          Borrow Karan Saeed       The Pragmatic Programmer      Andrew Hunt       2024-08-22
          Borrow Kinan Hamad       The Pragmatic Programmer      Andrew Hunt       2024-08-22
          Borrow Karan Saeed Data Structures and Algorithms Mark Allen Weiss       2024-08-22
          Borrow Kinan Hamad Data Structures and Algorithms Mark Allen Weiss       2024-08-22
          Return Karan Saeed Data Structures and Algorithms Mark Allen Weiss       2024-08-22
          Borrow Karan Saeed                     Clean Code Robert C. Martin       2024-08-22

In [37]:
# Display the user's borrowed books
print("\nBorrowed Books DataFrame for Karan Saeed:")
karan_saeed.borrowed_books

Borrowed Books DataFrame for Karan Saeed:

   Book Title            Author Borrow Date Return Date
0  Clean Code  Robert C. Martin  2024-08-22  2024-09-01

In [38]:
books_df.head()

,Title,Author,CopiesAvailable
1,Python Programming,John Doe,7
3,Machine Learning Basics,Michael Brown,0
4,Deep Learning with TensorFlow,Anna White,2
5,Artificial Intelligence: A Modern Approach,Peter Green,6
6,Introduction to Algorithms,Thomas H. Cormen,7

In [39]:
books_df.shape

(9, 3)

In [40]:
print(users_df.shape)
users_df.head()

(35, 7)

,First Name,Last Name,Age,Role,Borrowed Books,Fines,Gender
0,Leen,Samman,20,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
1,Amal,Taha,34,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
2,Amany,Awwad,22,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Female
3,Ahmad,Bilal,55,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male
4,Karam,Jallad,19,Regular,"Empty DataFrame\nColumns: [Book Title, First D...",0,Male

In [41]:
borrowed_books_df

,User,Title,Author,Borrow Date,Due Date
0,John Smith,Machine Learning Basics,Michael Brown,2024-08-22,2024-09-21
1,Laya abed,Data Science with Python,Jane Smith,2024-08-22,2024-09-01
2,Karan Saeed,The Pragmatic Programmer,Andrew Hunt,2024-08-22,2024-09-01
3,Kinan Hamad,The Pragmatic Programmer,Andrew Hunt,2024-08-22,2024-09-01
5,Karan Saeed,Clean Code,Robert C. Martin,2024-08-22,2024-09-01

In [42]:
havetoreturn_df

Empty DataFrame
Columns: [User, Book Title, Author, Original Due Date, Days Overdue, Fines]
Index: []

In [43]:
reservations_df

,Title,Author,Reserved By,Reservation Date,Queue Position,Notification Sent
0,Machine Learning Basics,Michael Brown,John Smith,2024-08-22,1,True
1,Machine Learning Basics,Michael Brown,layla ali,2024-08-22,2,False
2,Machine Learning Basics,Michael Brown,dina karam,2024-08-22,3,False
4,The Pragmatic Programmer,Andrew Hunt,Amjad Talal,2024-08-22,None,False

In [44]:
transaction_log_df

,Transaction Type,User,Title,Author,Transaction Date
0,Borrow,John Smith,Python Programming,John Doe,2024-08-22
1,Return,John Smith,Python Programming,John Doe,2024-08-22
2,Borrow,Leen Samman,Machine Learning Basics,Michael Brown,2024-08-22
3,Borrow,Leen Samman,Machine Learning Basics,Michael Brown,2024-08-22
4,Borrow,Leen Samman,Machine Learning Basics,Michael Brown,2024-08-22
5,Borrow,Leen Samman,Machine Learning Basics,Michael Brown,2024-08-22
6,Return,Leen Samman,Machine Learning Basics,Michael Brown,2024-08-22
7,Borrow,John Smith,Machine Learning Basics,Michael Brown,2024-08-22
8,Borrow,Laya abed,Data Science with Python,Jane Smith,2024-08-22
9,Borrow,Karan Saeed,The Pragmatic Programmer,Andrew Hunt,2024-08-22
10,Borrow,Kinan Hamad,The Pragmatic Programmer,Andrew Hunt,2024-08-22
11,Borrow,Karan Saeed,Data Structures and Algorithms,Mark Allen Weiss,2024-08-22
12,Borrow,Kinan Hamad,Data Structures and Algorithms,Mark Allen Weiss,2024-08-22
13,Return,Karan Saeed,Data Structures and Algorithms,Mark Allen Weiss,2024-08-22
14,Borrow,Karan Saeed,Clean Code,Robert C. Martin,2024-08-22